language: python

python:
  - 2.6
  - 2.7

before_install:
  - git submodule update --init --recursive
  - cd kafka-src
  - ./sbt clean update package assembly-package-dependency
  - cd -

install:
  pip install .

script:
  - python -m test.test_unit
  - python -m test.test_integration
