language: python

python: 2.7

before_install:
  - git submodule update --init --recursive
  - sudo apt-get install libsnappy-dev
  - ./build_integration.sh

install:
  - pip install tox
  - pip install .
  # Deal with issue on Travis builders re: multiprocessing.Queue :(
  # See https://github.com/travis-ci/travis-cookbooks/issues/155
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm

env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=pypy

script:
    - tox -e $TOX_ENV
    - KAFKA_VERSION=0.8.0 tox -e $TOX_ENV
    - KAFKA_VERSION=0.8.1 tox -e $TOX_ENV
